---
include:
   - board: nrfmicro_13
     shield: dongle_central_dongle rgbled_adapter dongle_display
     snippet: studio-rpc-usb-uart
     cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
     artifact-name: dongle_central_dongle
   - board: nrfmicro_13
     shield: dongle_central_left
     artifact-name: dongle_central_left
   - board: nrfmicro_13
     shield: dongle_peripheral_left 
     artifact-name: dongle_peripheral_left 
   - board: nrfmicro_13
     shield: dongle_peripheral_right 
     artifact-name: dongle_peripheral_right 
   - board: nrfmicro_13
     shield: settings_reset